export const blogPosts = [
  {
    slug: "bldc",
    title: "BLDC Motor Sürücü Tasarımı",
    date: "Mart 2024",
    image: "/bldc/daa8d918-d013-45f4-aafe-2657dc6f4d7c.jpg",
    description: "BLDC motor sürücü tasarımı ve uygulaması",
    content: "BLDC motor sürücü tasarımı ve uygulaması",
  },
  {
    slug: "buckconverter",
    title: "Buck Konvertör Tasarımı",
    date: "Nisan 2024",
    image: "/buckconverter/buck.jpg",
    description: "Buck konvertör tasarımı ve uygulaması",
    content: "Buck konvertör tasarımı ve uygulaması",
  },
  {
    slug: "boostconverter",
    title: "Boost Konvertör Tasarımı",
    date: "Mayıs 2024",
    image: "/boostconverter/boost.jpg",
    description: "Boost konvertör tasarımı ve uygulaması",
    content: "Boost konvertör tasarımı ve uygulaması",
  },
  {
    slug: "buckboostyazi",
    title: "Buck-Boost Konvertör Tasarımı",
    date: "Haziran 2024",
    image: "/buckboostyazi/buckboost.jpg",
    description: "Buck-Boost konvertör tasarımı ve uygulaması",
    content: "Buck-Boost konvertör tasarımı ve uygulaması",
  },
  {
    slug: "flyback",
    title: "Flyback Konvertör Tasarımı",
    date: "Temmuz 2024",
    image: "/flyback/flyback.jpg",
    description: "Flyback konvertör tasarımı ve uygulaması",
    content: "Flyback konvertör tasarımı ve uygulaması",
  },
  {
    slug: "matlabtoplc",
    title: "MATLAB ile PLC Programlama",
    date: "Ağustos 2024",
    image: "/matlabtoplc/logo.jpg",
    description: "MATLAB ile PLC programlama ve uygulaması",
    content: "MATLAB ile PLC programlama ve uygulaması",
  },
  {
    slug: "wattmetre",
    title: "Wattmetre Tasarımı",
    date: "Eylül 2024",
    image: "/wattmetre/wattmetre.jpg",
    description: "Wattmetre tasarımı ve uygulaması",
    content: "Wattmetre tasarımı ve uygulaması",
  },
]; 